name: novel_formatter
description: A dart package to format novels.
version: 0.0.1
repository: https://github.com/Meltryllis163/novel_formatter

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  fast_gbk: ^1.0.0
  chinese_number: ^1.0.2
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0