name: novel_formatter
description: A dart package to format novels.
version: 0.2.0
repository: https://github.com/Meltryllis163/novel_formatter

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  chinese_number: ^1.0.2
  logger: ^2.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0